INSERT INTO Requisiti(NomeReq, CodiceReq, Sistema, Importanza, Tipo, Descrizione) VALUES ("RC0F1", "1", "C", "0", "F", "L'utente deve potersi registrare all'applicativo cloud"),
("RC0F1.1", "1.1", "C", "0", "F", "Ogni utente deve essere identificato da una email"),
("RC0F1.1.1", "1.1.1", "C", "0", "F", "La email deve essere di formato valido"),
("RC0F1.2", "1.2", "C", "0", "F", "Nella procedura di registrazione ogni utente deve creare una password"),
("RC0F1.2.1", "1.2.1", "C", "0", "F", "Nella procedura di registrazione l'utente deve confermare la password"),
("RC0F1.2.2", "1.2.2", "C", "0", "F", "La password deve essere di almeno 6 caratteri"),
("RC0F1.3", "1.3", "C", "0", "F", "L'utente deve poter confermare i dati di registrazione"),
("RC0F1.4", "1.4", "C", "0", "F", "L'utente deve visualizzare un messaggio d'errore in caso di errori di inserimento"),
("RC0F2", "2", "C", "0", "F", "L'utente deve poter accedere all'applicativo cloud"),
("RC0F2.1", "2.1", "C", "0", "F", "L'utente accede con la propria email già registrata"),
("RC0F2.2", "2.2", "C", "0", "F", "L'utente accede con la password associata al proprio account"),
("RC0F2.3", "2.3", "C", "0", "F", "L'utente deve poter confermare i dati di autenticazione"),
("RC0F3", "3", "C", "0", "F", "L'applicazione cloud permette la gestione delle mappe"),
("RC0F3.1", "3.1", "C", "0", "F", "L'utente deve poter visualizzare l'elenco delle mappe a disposizione"),
("RC0F3.1.1", "3.1.1", "C", "0", "F", "Ogni mappa ha come nome il nome della località principale contenuta"),
("RC0F4", "4", "C", "0", "F", "L'utente deve poter ricercare delle mappe attraverso una chiave di ricerca"),
("RC0F4.1", "4.1", "C", "0", "F", "Per la ricerca di una mappa l'utente deve poter inserire una chiave di ricerca"),
("RC0F4.1.1", "4.1.1", "C", "0", "F", "Le mappe possono essere ricercate utilizzando il nome della mappa"),
("RC0F4.2", "4.2", "C", "0", "F", "L'utente deve poter avviare una ricerca dopo aver inserito una chiave di ricerca"),
("RC0F5", "5", "C", "0", "F", "Deve essere presente un elenco delle mappe preferite"),
("RC0F5.1", "5.1", "C", "0", "F", "L'utente deve poter visualizzare le mappe preferite"),
("RC0F5.1.1", "5.1.1", "C", "0", "F", "Ogni mappa preferita ha come nome il nome della località principale contenuta"),
("RC0F5.2", "5.2", "C", "0", "F", "L'utente deve poter aggiungere una o più mappe alle mappe preferite"),
("RC0F5.3", "5.3", "C", "0", "F", "L'utente deve poter rimuovere una o più mappe dalle mappe preferite"),
("RC1F6", "6", "C", "1", "F", "L'utente deve poter visualizzare le informazioni meteo in riferimento alla mappa desiderata"),
("RC1F6.1", "6.1", "C", "1", "F", "Le informazioni meteo visualizzate riguardano la condizione meteorologica, la temperatura massima e minima, l'intensità e la direzione del vento, la probabilità di precipitazioni e l'orario di tramonto del sole"),
("RC0F7", "7", "C", "0", "F", "Deve essere presente un elenco delle escursioni già effettuate"),
("RC0F7.1", "7.1", "C", "0", "F", "L'utente deve poter visualizzare l'elenco delle escursioni già effettuate"),
("RC0F7.2", "7.2", "C", "0", "F", "L'utente deve poter selezionare un'escursione già effettuata"),
("RC0F7.3", "7.3", "C", "0", "F", "L'utente deve poter visualizzare tutti i percorsi dell'escursione precedentemente selezionata"),
("RC0F7.3.1", "7.3.1", "C", "0", "F", "Le informazioni riguardanti un percorso effettuato sono: data dell'esperienza$_{G}$, ora di partenza ed arrivo, chilometri percorsi, tempo impiegato e POI visitati durante l'esperienza$_{G}$"),
("RC1F8", "8", "C", "1", "F", "L'utente deve poter condividere l'escursione precedentemente selezionata su Facebook$_{G}$"),
("RC1F8.1", "8.1", "C", "1", "F", "Le informazioni che possono essere condivise nel social network sono: data dell'esperienza$_{G}$, ora di partenza ed arrivo, chilometri percorsi, tempo impiegato, POI visitati durante l'esperienza$_{G}$ e mappa del escursione effettuato"),
("RC0F9", "9", "C", "0", "F", "L'applicazione cloud deve offrire la possibilità agli utenti di cambiare la propria password"),
("RC0F9.1", "9.1", "C", "0", "F", "Nella procedura di cambio password l'utente deve inserire la vecchia password"),
("RC0F9.2", "9.2", "C", "0", "F", "Nella procedura di cambio password l'utente deve inserire la nuova password"),
("RC0F9.2.1", "9.2.1", "C", "0", "F", "Nella procedura di cambio password l'utente deve confermare la nuova password"),
("RC0F9.3", "9.3", "C", "0", "F", "L'utente deve poter confermare i dati inseriti durante la procedura cambio password"),
("RC0F10", "10", "C", "0", "F", "L'utente deve poter gestire la registrazione del seriale dello smartwatch"),
("RC0F10.1", "10.1", "C", "0", "F", "L'utente, per associare lo smartwatch, deve poter inserire un nuovo seriale"),
("RC0F10.1.1", "10.1.1", "C", "0", "F", "L'utente deve poter confermare il seriale dello smartwatch per completare l'inserimento"),
("RC0F10.2", "10.2", "C", "0", "F", "L'utente deve poter rimuovere il seriale dello smartwatch già presente"),
("RC0F11", "11", "C", "0", "F", "E' garantita la possibilità all'utente di recuperare la propria password"),
("RC0F11.1", "11.1", "C", "0", "F", "Il recupero password deve avvenire tramite l'inserimento di una email registrata nel sistema"),
("RC0F11.1.1", "11.1.1", "C", "0", "F", "L'utente deve poter confermare i dati inseriti durante la procedura di recupero password"),
("RC0F11.2", "11.2", "C", "0", "F", "L'applicazione cloud deve inviare una email contenente la nuova password"),
("RC0F12", "12", "C", "0", "F", "L'utente deve poter uscire dall'applicativo cloud"),
("RS0F13", "13", "S", "0", "F", "L'utente deve poter scegliere un POI fra quelli del percorso in cui si trova"),
("RS0F13.1", "13.1", "S", "0", "F", "L'utente deve poter visualizzare l'elenco dei POI del percorso in cui si trova"),
("RS0F13.1.1", "13.1.1", "S", "0", "F", "L'elenco dei POI sarà costituito da: rifugi, ristori, luoghi di interesse naturalistico (punti panoramici, cascate, ecc.)"),
("RS0F13.2", "13.2", "S", "0", "F", "L'utente deve poter selezionare un POI dall'elenco visualizzato"),
("RS1F14", "14", "S", "1", "F", "L'utente deve poter visualizzare le informazioni meteo della mappa in uso"),
("RS1F14.1", "14.1", "S", "1", "F", "L'utente deve poter visualizzare un avviso che il meteo risulta non aggiornato"),
("RS1F14.2", "14.2", "S", "1", "F", "Le informazioni meteo visualizzate riguardano la condizione meteorologica, la temperatura massima e minima, l'intensità e la direzione del vento, la probabilità di precipitazioni e l'orario del tramonto del sole"),
("RS0F15", "15", "S", "0", "F", "L'utente deve poter visualizzare le informazioni di soccorso"),
("RS0F15.1", "15.1", "S", "0", "F", "Le informazioni di soccorso comprendono il numero del soccorso alpino, la posizione geografica in cui si trova l'utente e le indicazioni per chiedere soccorso nel caso non si disponga della rete telefonica (segnali acustici e luminosi)"),
("RS0F16", "16", "S", "0", "F", "L'applicazione smartwatch fornisce un sistema di navigazione, fornendo indicazioni sulla posizione dell’utente, km percorsi e distanza rimanente"),
("RS0F17", "17", "S", "0", "F", "L'utente deve poter operare col sistema di navigazione solo dopo aver selezionato un POI"),
("RS0F18", "18", "S", "0", "F", "L'utente deve poter avviare la navigazione"),
("RS0F18.1", "18.1", "S", "0", "F", "L'utente deve poter sospendere la navigazione già avviata"),
("RS0F18.2", "18.2", "S", "0", "F", "L'utente deve poter riprendere la navigazione precedentemente sospesa"),
("RS0F18.3", "18.3", "S", "0", "F", "L'utente deve poter terminare la navigazione precedentemente avviata o sospesa"),
("RS0F19", "19", "S", "0", "F", "L'utente deve poter visualizzare le informazioni di viaggio"),
("RS0F19.1", "19.1", "S", "0", "F", "L'utente deve poter visualizzare le coordinate geografiche della posizione in cui si trova"),
("RS0F19.2", "19.2", "S", "0", "F", "L'utente deve poter visualizzare l'altitudine a cui si trova"),
("RS0F19.3", "19.3", "S", "0", "F", "L'utente deve poter visualizzare la distanza percorsa dal momento in cui ha avviato la navigazione"),
("RS0F19.4", "19.4", "S", "0", "F", "L'utente deve poter visualizzare il tempo rimanente per raggiungere il POI selezionato"),
("RS0F20", "20", "S", "0", "F", "L'utente deve poter avviare la sincronizzazione tra smartwatch e cloud"),
("RS0F20.1", "20.1", "S", "0", "F", "L'applicazione smartwatch deve poter scaricare dal cloud le mappe preferite"),
("RS1F20.2", "20.2", "S", "1", "F", "L'applicazione smartwatch deve poter scaricare dal cloud le informazioni meteo riguardanti le mappe preferite"),
("RS0F20.3", "20.3", "S", "0", "F", "L'applicazione smartwatch deve poter caricare sul cloud le informazioni sui percorsi effettuati"),
("RS0F20.4", "20.4", "S", "0", "F", "L'applicazione smartwatch deve poter inviare lo stato di occupazione della sua memoria al cloud"),
("RS2F21", "21", "S", "2", "F", "L'utente deve poter visualizzare il proprio battito cardiaco"),
("RS2F22", "22", "S", "2", "F", "L'applicazione smartwatch deve poter comunicare con il dispositivo per il rilevamento dei battiti cardiaci"),
("RS0F23", "23", "S", "0", "F", "Il sistema registra in background il percorso effettuato, tracciando il segnale gps, il tempo trascorso e i battiti cardiaci se è presente la fascia cardiaca"),
("RC0F24", "24", "C", "0", "F", "L'utente deve poter chiudere la ricerca e tornare alla lista completa delle mappe"),
("RS1F25", "25", "S", "1", "F", "L'utente deve poter visualizzare un messaggio che indichi che il meteo non è aggiornato"),
("RS0F26", "26", "S", "0", "F", "L'utente deve poter visualizzare un avviso che lo avverta che non è disponibile alcun POI per mancanza di connessione GPS o perchè non si trova in un percorso di hiking della mappa selezionata"),
("RC0F27", "27", "C", "0", "F", "Il sistema garantisce la persistenza della scelta effettuata dall'utente riguardo le mappe preferite"),
("RC0F28", "28", "C", "0", "F", "Il sistema è in grado di gestire gli errori riguardanti l'inserimento dei dati da parte dell'utente riportando il sistema ad uno stato consistente"),
("RC0F29", "29", "C", "0", "F", "Il sistema garantisce la persistenza delle informazioni registrate dallo smartwatch"),
("RC0F30", "30", "C", "0", "F", "Il sistema garantisce che un seriale possa essere univocamente associato ad una sola utenza"),
("RC0F31", "31", "C", "0", "F", "L'utente deve poter selezionare una mappa dall'elenco completo delle mappe o dal risultato di ricerca di una mappa"),
("RC0F32", "32", "C", "0", "F", "L'utente deve poter visualizzare la mappa precedentemente selezionata"),
("RC0F33", "33", "C", "0", "F", "L'utente deve poter visualizzare la memoria disponibile del dispositivo smartwatch"),
("RC0F46", "46", "C", "0", "F", "L'utente deve poter visualizzare un messaggio che indichi che la memoria è insufficiente per scaricare tutti i dati da sincronizzare"),
("R0Q34", "34", "", "0", "Q", "Devono essere prodotti e rilasciati manuali d’uso ed ogni altra documentazione tecnica necessaria per l’utilizzo del prodotto"),
("R0Q35", "35", "", "0", "Q", "Il progetto verrà sviluppato seguendo il documento \textit{NormeDiProgetto\_v2.0.0}"),
("RC0V36", "36", "C", "0", "V", "L'applicazione cloud deve essere sviluppata usando il framework Spring versione 4.1.5"),
("RS0V37", "37", "S", "0", "V", "L'applicazione per smartwatch deve essere sviluppata per Android 4.4.2"),
("RS0V38", "38", "S", "0", "V", "L'applicazione per smartwatch è sviluppata specificamente per WearIT"),
("R0V39", "39", "", "0", "V", "La comunicazione fra smartwatch e cloud deve avvenire nel formato JSON"),
("RC2V40", "40", "C", "2", "V", "L'applicazione cloud deve essere sviluppata usando HTML5$_{G}$ e CSS3$_{G}$"),
("RS0V41", "41", "S", "0", "V", "L'applicazione per smartwatch deve essere utilizzabile totalmente off-line nella parte di esperienza$_{G}$"),
("RC0V42", "42", "C", "0", "V", "L'applicazione cloud deve disporre di un'interfaccia in lingua italiana"),
("RS0V43", "43", "S", "0", "V", "L'applicazione per smartwatch deve disporre di un'interfaccia in lingua italiana"),
("RC0V44", "44", "C", "0", "V", "L'applicazione cloud deve funzionare con versioni 41.x o superiori di Chrome"),
("RC0V45", "45", "C", "0", "V", "L'applicazione cloud deve funzionare con versioni 36.x o superiori di Firefox");